[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.122.0",
    "langchain-groq>=1.1.0",
    "mcp-use>=1.4.1",
    "openai>=2.8.1",
    "uvicorn>=0.38.0",
]
